#!/usr/bin/env bash
# AEA cold-start report — run this once, send back the one file it writes.
#
# This is the whole ask for someone trying AEA for the first time. It does not touch your data,
# does not install anything, and does not need the ~1.5 GB test dataset. It probes the machine,
# resolves a backend, runs the test suite, and writes a single Markdown file.
#
#   bash tools/env/deploy_report.sh
#   -> AEA_DEPLOY_REPORT.md
#
# Home directories and usernames are redacted to `~` before anything is written, so the report can
# be pasted or emailed. Read it before you send it — it is plain text and short.
#
# Options:
#   AEA_FETCH_DATA=1   also download the MNE sample dataset (~1.5 GB) and run the heavy
#                      regression tests. Off by default; the report says so either way.

set -u

OUT="${1:-AEA_DEPLOY_REPORT.md}"
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT" || exit 1

TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Pick an interpreter that actually WORKS, preferring one that can run the suite.
#
# Taking `python3` on faith is wrong in a way that produces a *false* failure report: on Windows,
# `python3` is a Microsoft Store stub that exists on PATH, satisfies `command -v`, and has no
# packages at all. On Linux/macOS the same thing happens with a bare system python next to the
# user's real conda/venv. The report then blames AEA for the wrong interpreter.
pick_python() {
  local best="" cand
  # An explicit AEA_PYTHON is an instruction, not a hint. Honour it if it runs at all — silently
  # substituting a "better" interpreter would hide exactly the environment the tester meant to
  # report on, and produce a report about a machine state nobody asked about.
  if [ -n "${AEA_PYTHON:-}" ]; then
    if "$AEA_PYTHON" -c 'import sys' >/dev/null 2>&1; then echo "$AEA_PYTHON"; return 0; fi
    echo "AEA_PYTHON is set to '$AEA_PYTHON' but it does not run." >&2
    return 1
  fi
  for cand in python3 python py; do
    command -v "$cand" >/dev/null 2>&1 || continue
    # a Store stub fails this: it exits non-zero and prints nothing
    "$cand" -c 'import sys; print(sys.version_info[0])' >/dev/null 2>&1 || continue
    [ -z "$best" ] && best="$cand"
    # `import mne` is NOT a sufficient check. An interpreter inside a conda env that was never
    # ACTIVATED imports numpy and mne happily -- numpy registers its own DLL directory -- and then
    # hard-crashes the process the first time scipy reaches LAPACK, because <env>/Library/bin is
    # not on the library search path. On Windows that is `Windows fatal exception: 0xc06d007f`,
    # and it surfaces only in the one test that does PCA whitening: 6 of 7 pass first. Same class
    # as the Store python3 stub -- present but unusable -- except it fails much later, where the
    # report would blame AEA. So probe the operation that actually breaks.
    if "$cand" -c 'import pytest, mne' >/dev/null 2>&1 \
       && "$cand" -c 'import scipy.linalg as L, numpy as N; L.svd(N.eye(2))' >/dev/null 2>&1; then
      echo "$cand"; return 0
    fi
  done
  [ -n "$best" ] && { echo "$best"; return 0; }
  return 1
}

PY="$(pick_python)" || {
  echo "No working Python found on PATH (tried AEA_PYTHON, python3, python, py)." >&2
  echo "Install Python 3.10+ with: pip install mne numpy scipy pytest" >&2
  exit 1
}

# Report missing requirements up front, so a blocked run says WHY rather than just failing.
MISSING=""
for mod in pytest mne numpy scipy; do
  "$PY" -c "import $mod" >/dev/null 2>&1 || MISSING="$MISSING $mod"
done
MISSING="${MISSING# }"

# A home path shows up in more than one SHAPE. Matching only the literal one leaked a real
# username on Windows via an embedded JSON's escaped "C:\\Users\\name"; the same applies to any
# Python repr here. Redact the shapes, then sweep the bare username as a backstop.
_U="$(id -un)"
redact() {
  sed -e "s|$HOME|~|g" \
      -e "s|/home/${_U}|~|g" \
      -e "s|/Users/${_U}|~|g" \
      -e "s|$(printf '%s' "$HOME" | sed 's|/|\\\\|g')|~|g" \
      -e "s|\\b${_U}\\b|<user>|g"
}
section() { printf '\n## %s\n\n' "$1" >> "$OUT"; }

echo "AEA cold-start report -> $OUT"
echo "(this takes a couple of minutes; nothing is uploaded, it just writes a file)"

: > "$OUT"
{
  echo "# AEA cold-start report"
  echo
  echo "Generated by \`tools/env/deploy_report.sh\`. Paths are redacted to \`~\`."
} >> "$OUT"

# ---------------------------------------------------------------- machine
section "Machine"
{
  echo '```'
  echo "os          : $(uname -s) $(uname -r) $(uname -m)"
  echo "shell       : ${SHELL:-unknown}"
  echo "python      : $($PY -c 'import sys; print(sys.version.split()[0], "at", sys.executable)' 2>&1 | redact)"
  echo "  (chosen as : $PY)"
  echo "required    : $([ -z "$MISSING" ] && echo 'pytest, mne, numpy, scipy all present' || echo "MISSING -> $MISSING")"
  echo "git commit  : $(git rev-parse --short HEAD 2>/dev/null \
                        || sed -n '1s/^\([0-9a-f]\{7\}\).*/\1 (from archive)/p' tools/env/ARCHIVE_VERSION 2>/dev/null \
                        || echo 'unknown')"
  echo "fetch data  : ${AEA_FETCH_DATA:-0}"
  echo '```'
} | redact >> "$OUT"

# A blocked run must say what is missing and how to fix it — not just fail. Otherwise the tester
# sends back a report that blames AEA for their own missing pytest, which helps nobody.
if [ -n "$MISSING" ]; then
  {
    echo
    echo "## BLOCKED — required packages missing"
    echo
    echo "This machine's Python is missing: **$MISSING**"
    echo
    echo 'Install them and re-run:'
    echo
    echo '```bash'
    echo "$PY -m pip install $MISSING"
    echo "bash tools/env/deploy_report.sh"
    echo '```'
    echo
    echo "If you have a conda env or venv with these already, activate it first, or point the"
    echo "script at it directly:"
    echo
    echo '```bash'
    echo "AEA_PYTHON=/path/to/that/python bash tools/env/deploy_report.sh"
    echo '```'
    echo
    echo "**This is not an AEA failure** — nothing was tested. Please send the report anyway if"
    echo "the instructions were unclear about the prerequisites; that is a finding too."
  } | redact >> "$OUT"
  echo
  echo "BLOCKED: missing $MISSING"
  echo "  $PY -m pip install $MISSING"
  echo "Report written anyway: $ROOT/$OUT"
  exit 2
fi

# ---------------------------------------------------------------- step 1: env probe
section "1. Environment probe"
PROBE_OK=0
if bash tools/env/check_env.sh "$TMP/ENVIRONMENT.json" > "$TMP/probe.log" 2>&1; then
  if $PY -c "import json,sys; json.load(open('$TMP/ENVIRONMENT.json'))" 2>/dev/null; then
    PROBE_OK=1
    echo "**PASS** — wrote a valid \`ENVIRONMENT.json\`." >> "$OUT"
  else
    echo "**FAIL** — the probe ran but its output is not valid JSON. Every skill reads this file first." >> "$OUT"
  fi
else
  echo "**FAIL** — the probe exited non-zero." >> "$OUT"
fi
{
  echo
  echo '```'
  cat "$TMP/probe.log" | redact
  echo '```'
  echo
  echo "<details><summary>full ENVIRONMENT.json</summary>"
  echo
  echo '```json'
  cat "$TMP/ENVIRONMENT.json" 2>/dev/null | redact
  echo '```'
  echo
  echo "</details>"
} >> "$OUT"

# ---------------------------------------------------------------- step 2: backend resolution
section "2. Backend resolution"
RESOLVE_OK=0
if $PY tools/env/resolve_backend.py --capability erp.preprocess_average \
      --env "$TMP/ENVIRONMENT.json" --out "$TMP/BACKEND_RESOLUTION.md" > "$TMP/resolve.log" 2>&1; then
  RESOLVE_OK=1
  echo "**PASS** — resolved a backend and wrote the record." >> "$OUT"
elif grep -q "^Traceback" "$TMP/resolve.log"; then
  # A crash and a refusal both exit non-zero. Reporting a crash as "a legitimate outcome" is the
  # same silent-degradation failure this project exists to prevent -- one layer up, in the report
  # itself. Distinguish them: a refusal prints "ERROR: ..."; a crash prints a traceback.
  echo "**CRASH** — the resolver raised an unhandled exception. This is a defect, NOT the" >> "$OUT"
  echo "designed refusal. The traceback below is the finding." >> "$OUT"
else
  echo "**Resolver declined.** That is a legitimate outcome (it refuses rather than degrading" >> "$OUT"
  echo "silently); the message below says what is missing." >> "$OUT"
fi
{
  echo
  echo '```'
  cat "$TMP/resolve.log" | redact
  echo '```'
  echo
  echo "<details><summary>candidates considered</summary>"
  echo
  sed -n '/## Candidates considered/,/^## /p' "$TMP/BACKEND_RESOLUTION.md" 2>/dev/null \
    | sed '$d' | redact
  echo
  echo "</details>"
} >> "$OUT"

# ---------------------------------------------------------------- step 3: test suite
section "3. Test suite"
$PY -m pytest tools/tests/ -q -rs > "$TMP/pytest.log" 2>&1
RC=$?
SUMMARY="$(grep -E "[0-9]+ (passed|failed|error)" "$TMP/pytest.log" | tail -1)"
# pytest can die before it ever prints a summary line (missing module, collection crash, bad
# interpreter). Falling back to an empty string there is how a failing report ends up blank —
# which is the one outcome that makes the whole exercise worthless, since a failure is the
# result we actually want back.
[ -z "$SUMMARY" ] && SUMMARY="no pytest summary line — the run died before reporting (see below)"

if [ "$RC" -eq 0 ]; then
  echo "**PASS** — \`$SUMMARY\`" >> "$OUT"
else
  echo "**FAIL** (exit $RC) — \`$SUMMARY\`" >> "$OUT"
fi
{
  echo
  echo "Skips are expected when large datasets are absent; they are listed below."
  echo
  echo '```'
  FILTERED="$(grep -E "SKIPPED|FAILED|ERROR|passed|failed" "$TMP/pytest.log" | head -40)"
  if [ -n "$FILTERED" ]; then
    printf '%s\n' "$FILTERED" | redact
  else
    echo "(no test-result lines at all — raw output below)"
  fi
  echo '```'
} >> "$OUT"

if [ "$RC" -ne 0 ]; then
  {
    echo
    echo "<details><summary>failure detail</summary>"
    echo
    echo '```'
    DETAIL="$(grep -A6 -E "^(FAILED|ERROR)|^E " "$TMP/pytest.log" | head -120)"
    # Always fall back to the raw tail. An empty <details> block is worse than a noisy one.
    if [ -n "$DETAIL" ]; then printf '%s\n' "$DETAIL" | redact; else tail -60 "$TMP/pytest.log" | redact; fi
    echo '```'
    echo
    echo "</details>"
  } >> "$OUT"
fi

# ---------------------------------------------------------------- verdict
section "Verdict"
OVERALL_RC=1
if [ "$PROBE_OK" -eq 1 ] && [ "$RESOLVE_OK" -eq 1 ] && [ "$RC" -eq 0 ]; then
  OVERALL_RC=0
fi
{
  if [ "$OVERALL_RC" -eq 0 ]; then
    echo "**PASS** — environment probe, backend resolution, and test suite completed."
  else
    echo "**NOT READY** — one or more stages failed or declined; see sections 1–3."
  fi
  echo
  echo "Please send back this file (\`$OUT\`) and, if anything failed, say what you expected"
  echo "to happen. A failure here is the useful result: it is a defect on a machine that is not"
  echo "the developer's, which is exactly what this report exists to find."
} >> "$OUT"

# Verify our own redaction before telling anyone to send the file. A guard that is never run is
# indistinguishable from one that passes, which is exactly how the PowerShell side gave a false
# all-clear on its first real Windows run.
if [ -n "${_U}" ] && grep -qF "${_U}" "$OUT" 2>/dev/null; then
  echo
  echo "WARNING: '${_U}' still appears in $OUT on line(s): $(grep -nF "${_U}" "$OUT" | cut -d: -f1 | tr '\n' ' ')"
  echo "Redaction did not catch every form. Remove those lines before sending, and tell the"
  echo "maintainer which shape leaked -- that is itself a finding."
fi

echo
echo "Done. Send back: $ROOT/$OUT"
[ "$OVERALL_RC" -eq 0 ] && echo "Result: PASS ($SUMMARY)" || echo "Result: NOT READY (see report)"
exit "$OVERALL_RC"
